---
- name: Configure EC2 instance with Docker, Docker Compose, and Node.js
  hosts: ec2_instances
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install necessary packages
      apt:
        name:
          - docker.io
          - docker-compose
        state: present

    - name: Start Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Install Node.js and npm
      shell: |
        curl -sL https://deb.nodesource.com/setup_22.x | sudo -E bash -
        sudo apt-get install -y nodejs

    - name: Verify Node.js installation
      command: node -v
      register: node_version

    - name: Verify npm installation
      command: npm -v
      register: npm_version

    - name: Print Node.js version
      debug:
        msg: "Node.js version: {{ node_version.stdout }}"

    - name: Print npm version
      debug:
        msg: "npm version: {{ npm_version.stdout }}"

    - name: Install necessary npm packages globally
      npm:
        name: pm2
        global: yes
    - name: Copy Docker Compose file
      copy:
        src: ./docker-compose.yaml
        dest: /home/ubuntu/docker-compose.yaml

    - name: Bring up Docker Compose services
      shell: |
        cd /home/ubuntu
        docker-compose up -d
