- name: Update apt cache and install Docker, Docker Compose, Node.js, and Python
  hosts: ec2_instances
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Node.js and npm using NodeSource
      shell: |
        curl -sL https://deb.nodesource.com/setup_22.x | sudo -E bash -
        sudo apt-get install -y nodejs

    - name: Install necessary packages including Docker and Python
      apt:
        name:
          - docker.io
          - python3
          - python3-pip
        state: present
        update_cache: yes

    - name: Install Docker Compose
      shell: |
        sudo curl -L "https://github.com/docker/compose/releases/download/v2.11.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

    - name: Start Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Install npm packages globally
      npm:
        name: pm2
        global: yes

    - name: Install Python Docker SDK
      pip:
        name: docker==5.0.3

    - name: Check Docker version
      command: docker --version
      register: docker_version

    - name: Print Docker version
      debug:
        msg: "Docker version: {{ docker_version.stdout }}"

    - name: Check Docker Compose version
      command: docker-compose --version
      register: docker_compose_version

    - name: Print Docker Compose version
      debug:
        msg: "Docker Compose version: {{ docker_compose_version.stdout }}"

    - name: Check Docker service status
      systemd:
        name: docker
        state: started
        enabled: yes
      register: docker_service_status

    - name: Print Docker service status
      debug:
        msg: "Docker service status: {{ docker_service_status }}"

    - name: Copy Docker Compose file
      copy:
        src: ./docker-compose.yaml
        dest: /home/ubuntu/docker-compose.yaml

    - name: Bring up Docker Compose services
      shell: |
        cd /home/ubuntu
        docker-compose up -d
      register: docker_compose_output
      failed_when: docker_compose_output.rc != 0

    - name: Print Docker Compose output
      debug:
        msg: "Docker Compose output: {{ docker_compose_output.stdout }} {{ docker_compose_output.stderr }}"
